# .travis.yml

dist: xenial

language: python

cache: pip

matrix:
    allow_failures:
        - python: "nightly"
        
install:
    - pip install codecov
    - pip install coverage

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      
  - "3.7"
  - "3.8"
  - "3.8-dev"  
  - "nightly"
  
script: python3 timetravel.pyc < .test

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - coverage run timetravel.pyc < .test
  - codecov
